package com.example.apexapp.Model

data class UserX(
    val a_pass: String,
    val android_token: Any,
    val college_name: String,
    val connection_key: Any,
    val contact_no: String,
    val course_id: String,
    val description: String,
    val education: String,
    val email: String,
    val first_name: String,
    val gid: String,
    val group_name: String,
    val last_name: String,
    val password: String,
    val payment_status: String,
    val photo: Any,
    val price: String,
    val registered_date: String,
    val su: String,
    val subscription_expired: String,
    val uid: String,
    val updated_date: String,
    val user_status: String,
    val valid_for_days: String,
    val verify_code: String,
    val web_token: String,
    val wp_user: String
)